<?php

########################################################################
# Extension Manager/Repository config file for ext: "sfsvgapi"
#
# Auto generated by Extension Builder 2012-07-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SF SVG API',
	'description' => 'With help of this extension you get a SVG API for your extensions',
	'category' => 'plugin',
	'author' => 'Stefan Froemken',
	'author_email' => 'firma@sfroemken.de',
	'author_company' => 'Stefan Froemken',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>